### ISSUE TITLE
What GPU is it based on to obtain 65.3 fps

### ISSUE THREAD

**Issue by 464hee** [PJLallen/UDUN#1]

**Comment by PJLallen** [comment]
Hi, we use a single RTX 3090 GPU to inference our model. Actually, wo also adopt one 2080ti GPU to achieve the fps score， which can obtain similar results.
More details can refer to our paper: https://arxiv.org/abs/2307.14052. Thanks for your attention.

**Comment by 464hee** [comment]
ok
