### ISSUE TITLE
UDUN-R18

### ISSUE THREAD

**Issue by cowrturn** [PJLallen/UDUN#2]
[UDUN-R18](https://drive.google.com/file/d/1c_u6zw-6W9OBmefu0wiDL73IbkTitoJu/view?usp=drive_link)
This weight I only loaded successfully on resnet50
--------这个权重好像是resnet50的而不是resnet18

**Comment by PJLallen** [comment]
Sorry, we haven't sorted it out yet. Thanks for your attention!

**Comment by cowrturn** [comment]
Looking forward to your work, a lightweight network helps with fast detection, so I'm even more excited about resnet18!
-----
期待你们的工作展现，轻量化的网络更快完成检测，因此我更加期待resnet18的预训练权重，谢谢。

**Comment by minimaxzzj** [comment]
> [UDUN-R18](https://drive.google.com/file/d/1c_u6zw-6W9OBmefu0wiDL73IbkTitoJu/view?usp=drive_link) This weight I only loaded successfully on resnet50 --------这个权重好像是resnet50的而不是resnet18
@cowrturn 
Hello, thank you for your support of our project. We wonder if you have downloaded our pre-trained weights, i.e., UDUN-R18, UDUN-R34, and UDUN-R50, as we have unfortunately lost our previous copies. We would be extremely grateful if you could send us a copy. Email: zhouzhangjun@hust.edu.cn or zhangjunzhou888@gmail.com

感谢您的关注和提醒，不知您是否已经下载过这些权重（UDUN-R18, UDUN-R34, and UDUN-R50），如有备份将不胜感激！
